data_directory: "screenshots"

### 1代表灰度处理， 2代表二值化处理，如果需要使用二值化，需要将2放到前面, 0不使用
image_compress_level:
  - 0
  - 1
  - 2

### 0 表示普通识别，配合compress_level 1使用
### 1 标识精确识别，精确识别建议配合image_compress_level 2使用
api_version:
  - 0
  - 1

## 图像比例裁剪区域, (left, top, right, bottom)
## 最终裁剪区域可表示为 (image_width * left, image_height * top, image_width * right, image_height * bottom)
crop_areas:
    '百万英雄':
      - 0.05
      - 0.115
      - 0.949
      - 0.656
    '冲顶大会':
      - 0.074
      - 0.156
      - 0.926
      - 0.573
    "芝士超人":
      - 0.0509
      - 0.156
      - 0.949
      - 0.625
    "UC答题":
      - 0.074
      - 0.186
      - 0.926
      - 0.683
    "知乎头脑王者":
      - 0.127
      - 0.323
      - 0.840
      - 0.930
    '百度贴吧百万富翁':
      - 0.05
      - 0.115
      - 0.949
      - 0.656
    '百度好看视频极速挑战':
       - 0.05
       - 0.115
       - 0.949
       - 0.656
### 知乎中任然出现，把左右两边的分数和在选项中了，贴吧的出贴人的帐号去掉

### baidu orc
app_id: "10683349"
app_key: "XB6xqK0EWjRl7Ithmmwu2QGg"
app_secret: "3GwEF0PE0YDMfDwUqysqwkxIRNLUbbM7 "

### ocr.space
api_key: "6c851da45688957"

### 默认使用百度，每天封顶500次
### 如果你想要使用ocr.space的话，将ocrspace移动到前面,每个api_key每月支持25000次调用
prefer:
  - baidu
  - ocrspace

### enable chrome
enable_chrome: true

### 是否使用夜神模拟器 for android
use_monitor: true

### 是否使用模拟器 for ios
use_ios_monitor: false

### 是否图片缩放
enable_scale: true
